### ISSUE TITLE
fpsync status/progress reporting does not work correctly

### ISSUE THREAD

**Issue by ispringer** [martymac/fpart#48] opened 2023-06-22 20:30 UTC
When estimating time remaining, it appears to only consider whether the jobs were submitted, not how much longer remaining jobs will take. Here's an example:

```
1687462151 <=== [QMGR] Done submitting jobs. Waiting for them to finish.
1687462190 <= [QMGR] Job 23067:248:local finished
1687462199 <= [QMGR] Job 27451:280:local finished

1687462200 <=== Parts done: 281/281 (100%), remaining: 0
1687462200 <=== Time elapsed: 1025s, remaining: ~0s (~3s/job)

1687462281 <=== Parts done: 281/281 (100%), remaining: 0
1687462281 <=== Time elapsed: 1106s, remaining: ~0s (~3s/job)

# 40 minutes pass, but status does not change at all aside from Time elapsed increasing
# during this time the final part is being processed. this part is 10x bigger than any other part due to containing a single huge file

1687464541 <= [QMGR] Job 5504:1:local finished
1687464541 <=== [QMGR] Queue processed
1687464541 <=== Parts done: 281/281 (100%), remaining: 0
1687464541 <=== Time elapsed: 3366s, remaining: ~0s (~11s/job)
1687464541 <=== Fpsync completed without error in 3366s.
1687464541 <=== End time: Thu Jun 22 20:09:01 UTC 2023
```

**Comment by martymac** [comment] 2023-06-23 10:47
Hello Ian,

Thanks for your report.

Remaining time is calculated using observed (overall) average time per job and remaining jobs count.

There is indeed a problem in what you show here. Fpsync should be showing 1 remaining job and an associated time (!= '0s').

The problem is the last running processes (in your case, the last one) are accounted as 'done' because part of the work dir. I'll fix that ASAP, thanks!

As a side note, if partitions are not balanced (what you are observing here), remaining time will probably not be accurate, but at least it should not be '0s'.

Best regards,

Ganael.

**Comment by martymac** [comment] 2023-06-26 10:09
Hello Ian,

ETA should be fixed with latest commit. Can you give it a try ?

Best regards,

Ganael.

**Comment by martymac** [comment] 2023-06-27 05:49
Thanks for your feedback!

Regarding ^T, it only works on FreeBSD. As you said, you'll have to send the signal manually under Linux :)

Thanks again for your report, I'll close that issue. Feel free to reopen it if necessary.

Cheers,

Ganael.

**Closed by martymac** 2023-06-27 05:49 UTC
